language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran libhdf5-serial-1.8.4 libhdf5-serial-dev
install:
  - pip install -r requirements.txt .
script:
  - nosetests
  - biom show-install-info
